language: python
dist: xenial

cache:
  directories:
    - $HOME/geosinstall
    - ~/.cache/pip

matrix:
  include:
    - python: "2.7"
      env:
        GEOSVERSION="3.4.3"
        SPEEDUPS=1
        NUMPY=1
    - python: "2.7"
      env:
        GEOSVERSION="3.4.3"
        SPEEDUPS=0
        NUMPY=1
    - python: "2.7"
      env:
        GEOSVERSION="3.4.3"
        SPEEDUPS=0
        NUMPY=0
    - python: "3.5"
      env:
        GEOSVERSION="3.5.2"
        SPEEDUPS=1
        NUMPY=1
    - python: "3.5"
      env:
        GEOSVERSION="3.5.2"
        SPEEDUPS=0
        NUMPY=1
    - python: "3.5"
      env:
        GEOSVERSION="3.5.2"
        SPEEDUPS=0
        NUMPY=0
    - python: "3.6"
      env:
        GEOSVERSION="3.6.4"
        SPEEDUPS=1
        NUMPY=1
    - python: "3.6"
      env:
        GEOSVERSION="3.6.4"
        SPEEDUPS=0
        NUMPY=1
    - python: "3.6"
      env:
        GEOSVERSION="3.6.4"
        SPEEDUPS=0
        NUMPY=0
    - python: "3.7"
      env:
        GEOSVERSION="3.7.3"
        SPEEDUPS=1
        NUMPY=1
    - python: "3.7"
      env:
        GEOSVERSION="3.7.3"
        SPEEDUPS=0
        NUMPY=1
    - python: "3.7"
      env:
        GEOSVERSION="3.7.3"
        SPEEDUPS=0
        NUMPY=0
    - python: "3.8"
      env:
        GEOSVERSION="3.8.1"
        SPEEDUPS=1
        NUMPY=1
    - python: "3.8"
      env:
        GEOSVERSION="3.8.1"
        SPEEDUPS=0
        NUMPY=1
    - python: "3.8"
      env:
        GEOSVERSION="3.8.1"
        SPEEDUPS=0
        NUMPY=0
    - python: "3.8-dev"
      env:
        GEOSVERSION="master"
        SPEEDUPS=1
        NUMPY=1
  allow_failures:
    - python: "3.8-dev"
      env:
        GEOSVERSION="master"
        SPEEDUPS=1
        NUMPY=1

before_install:
  - ./ci/travis/install_geos.sh
  - pip install --upgrade pip
  # if building with speedups install cython
  - if [ "$SPEEDUPS" == "1" ]; then pip install --install-option="--no-cython-compile" https://github.com/cython/cython/archive/04d918f684404375390657d12ecb53346d66c93d.zip; fi
  # if testing without numpy explicitly remove it
  - if [ "$NUMPY" == "0" ]; then pip uninstall --yes numpy; fi
  # convert SPEEDUPS to --with-speedups/--without-speedups
  - if [ "$SPEEDUPS" == "1" ]; then SPEEDUPS_FLAG=--with-speedups; else SPEEDUPS_FLAG=--without-speedups; fi
  - pip install --upgrade coveralls pytest-cov pytest>=3.8

install:
  - export GEOS_CONFIG=$HOME/geosinstall/geos-$GEOSVERSION/bin/geos-config
  - pip install -v -e .[all]

script:
  - python -m pytest --cov shapely --cov-report term-missing "${SPEEDUPS_FLAG}"

after_success:
  - coveralls || echo "!! intermittent coveralls failure"

notifications:
    email: false
